# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module ModuleFormat
    module ModResource
      # The inputs to a {Resource}.
      class ResourceArgs < ::Pulumi::Args
        property :text
      end

      class Resource < ::Pulumi::CustomResource
        TYPE = "module-format:mod_Resource:Resource"

        def initialize(name, text: nil, opts: nil, &block)
          args = ResourceArgs.build({
            text: text,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def text
          output("text")
        end
      end
    end
  end
end
