# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Flaky
    # The inputs to a {FlakyCreate}.
    class FlakyCreateArgs < ::Pulumi::Args
    end

    class FlakyCreate < ::Pulumi::CustomResource
      TYPE = "flaky:index:FlakyCreate"

      def initialize(name, opts: nil, &block)
        args = FlakyCreateArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end
    end
  end
end
