# frozen_string_literal: true

source "https://rubygems.org"

gem "pulumi-output", path: "ROOT/artifacts/pulumi-output"
gem "pulumi", path: "ROOT/artifacts/pulumi"
gem "pulumi-simple", path: "ROOT/artifacts/pulumi-simple"
