# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "snake_names/cool_module/another_resource"
require_relative "snake_names/cool_module/some_resource"
