# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/callback.proto

require 'google/protobuf'


descriptor_data = "\n\x15pulumi/callback.proto\x12\tpulumirpc\"F\n\x08\x43\x61llback\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x1b\n\x13\x61\x63\x63\x65pts_byte_string\x18\x03 \x01(\x08\"7\n\x15\x43\x61llbackInvokeRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\"*\n\x16\x43\x61llbackInvokeResponse\x12\x10\n\x08response\x18\x01 \x01(\x0c\x32\\\n\tCallbacks\x12O\n\x06Invoke\x12 .pulumirpc.CallbackInvokeRequest\x1a!.pulumirpc.CallbackInvokeResponse\"\x00\x42\x34Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  Callback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.Callback").msgclass
  CallbackInvokeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.CallbackInvokeRequest").msgclass
  CallbackInvokeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.CallbackInvokeResponse").msgclass
end
