# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/converter.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "converter_pb"

module Pulumirpc
  module Converter
    # Converter is a service for converting between other ecosystems and Pulumi.
    # This is currently unstable and experimental.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.Converter'

      # ConvertState converts state from the target ecosystem into a form that can be imported into Pulumi.
      rpc :ConvertState, ::Pulumirpc::ConvertStateRequest, ::Pulumirpc::ConvertStateResponse
      # ConvertProgram converts a program from the target ecosystem into a form that can be used with Pulumi.
      rpc :ConvertProgram, ::Pulumirpc::ConvertProgramRequest, ::Pulumirpc::ConvertProgramResponse
      # ConvertSnippet generates a single PCL file from a single source file in the target ecosystem. It is used when
      # callers need to convert a small source fragment, such as an input file, rather than a full Pulumi program.
      rpc :ConvertSnippet, ::Pulumirpc::ConvertSnippetRequest, ::Pulumirpc::ConvertSnippetResponse
    end

    Stub = Service.rpc_stub_class
  end
end
