# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/engine.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'


descriptor_data = "\n\x13pulumi/engine.proto\x12\tpulumirpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"y\n\nLogRequest\x12(\n\x08severity\x18\x01 \x01(\x0e\x32\x16.pulumirpc.LogSeverity\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03urn\x18\x03 \x01(\t\x12\x10\n\x08streamId\x18\x04 \x01(\x05\x12\x11\n\tephemeral\x18\x05 \x01(\x08\"\x18\n\x16GetRootResourceRequest\"&\n\x17GetRootResourceResponse\x12\x0b\n\x03urn\x18\x01 \x01(\t\"%\n\x16SetRootResourceRequest\x12\x0b\n\x03urn\x18\x01 \x01(\t\"\x19\n\x17SetRootResourceResponse\"Q\n\x15StartDebuggingRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x1bRequirePulumiVersionRequest\x12\x1c\n\x14pulumi_version_range\x18\x01 \x01(\t\"\x1e\n\x1cRequirePulumiVersionResponse*:\n\x0bLogSeverity\x12\t\n\x05\x44\x45\x42UG\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\xb1\x03\n\x06\x45ngine\x12\x36\n\x03Log\x12\x15.pulumirpc.LogRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x0fGetRootResource\x12!.pulumirpc.GetRootResourceRequest\x1a\".pulumirpc.GetRootResourceResponse\"\x00\x12Z\n\x0fSetRootResource\x12!.pulumirpc.SetRootResourceRequest\x1a\".pulumirpc.SetRootResourceResponse\"\x00\x12L\n\x0eStartDebugging\x12 .pulumirpc.StartDebuggingRequest\x1a\x16.google.protobuf.Empty\"\x00\x12i\n\x14RequirePulumiVersion\x12&.pulumirpc.RequirePulumiVersionRequest\x1a\'.pulumirpc.RequirePulumiVersionResponse\"\x00\x42\x34Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  LogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.LogRequest").msgclass
  GetRootResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRootResourceRequest").msgclass
  GetRootResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRootResourceResponse").msgclass
  SetRootResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SetRootResourceRequest").msgclass
  SetRootResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SetRootResourceResponse").msgclass
  StartDebuggingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.StartDebuggingRequest").msgclass
  RequirePulumiVersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RequirePulumiVersionRequest").msgclass
  RequirePulumiVersionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RequirePulumiVersionResponse").msgclass
  LogSeverity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.LogSeverity").enummodule
end
