# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/errors.proto

require 'google/protobuf'


descriptor_data = "\n\x13pulumi/errors.proto\x12\tpulumirpc\"1\n\nErrorCause\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstackTrace\x18\x02 \x01(\t\"\x8d\x01\n\x14InputPropertiesError\x12=\n\x06\x65rrors\x18\x01 \x03(\x0b\x32-.pulumirpc.InputPropertiesError.PropertyError\x1a\x36\n\rPropertyError\x12\x15\n\rproperty_path\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\tB4Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  ErrorCause = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.ErrorCause").msgclass
  InputPropertiesError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.InputPropertiesError").msgclass
  InputPropertiesError::PropertyError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.InputPropertiesError.PropertyError").msgclass
end
