# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/events.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2025, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "events_pb"

module Pulumirpc
  module Events
    # Events is a service for receiving engine events over gRPC.
    # This service allows the Pulumi CLI to send engine events to clients
    # (such as the Automation API) over a gRPC stream instead of writing them to
    # a file on the filesystem and reading them from there.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.Events'

      # StreamEvents allows the client to stream multiple engine events to the server.
      # The client sends multiple EventRequest messages over the stream, and the server
      # processes them as they arrive. When the client is done sending events, it closes
      # the stream.
      rpc :StreamEvents, stream(::Pulumirpc::EventRequest), ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
