# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/events.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'


descriptor_data = "\n\x13pulumi/events.proto\x12\tpulumirpc\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0c\x45ventRequest\x12\r\n\x05\x65vent\x18\x01 \x01(\t2M\n\x06\x45vents\x12\x43\n\x0cStreamEvents\x12\x17.pulumirpc.EventRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x42\x34Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  EventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.EventRequest").msgclass
end
