# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/language.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "language_pb"

module Pulumirpc
  module LanguageRuntime
    # The LanguageRuntime service defines a standard interface for [language hosts/runtimes](languages). At a high level, a
    # language runtime provides the ability to execute programs, install and query dependencies, and generate code for a
    # specific language.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.LanguageRuntime'

      # `Handshake` is the first call made by the engine to a language host. It is used to pass the engine's address to
      # the language host so that it may establish its own connections back, and to establish protocol configuration that
      # will be used to communicate between the two parties.
      rpc :Handshake, ::Pulumirpc::LanguageHandshakeRequest, ::Pulumirpc::LanguageHandshakeResponse
      # `GetRequiredPlugins` computes the complete set of anticipated [plugins](plugins) required by a Pulumi program.
      # Among other things, it is intended to be used to pre-install plugins before running a program with
      # [](pulumirpc.LanguageRuntime.Run), to avoid the need to install them on-demand in response to [resource
      # registrations](resource-registration) sent back from the running program to the engine.
      #
      # :::{important}
      # The use of `GetRequiredPlugins` is deprecated in favour of [](pulumirpc.LanguageRuntime.GetRequiredPackages),
      # which returns more granular information about which plugins are required by which packages.
      # :::
      rpc :GetRequiredPlugins, ::Pulumirpc::GetRequiredPluginsRequest, ::Pulumirpc::GetRequiredPluginsResponse
      # `GetRequiredPackages` computes the complete set of anticipated [packages](pulumirpc.PackageDependency) required
      # by a program or plugin. It is used to pre-install packages before running a program with
      # [](pulumirpc.LanguageRuntime.Run), to avoid the need to install them on-demand in response to [resource
      # registrations](resource-registration) sent back from the running program to the engine. Moreover, when importing
      # resources into a stack, it is used to determine which plugins are required to service the import of a given
      # resource, since given the presence of [parameterized providers](parameterized-providers), it is not in general
      # true that a package name corresponds 1:1 with a plugin name. It replaces
      # [](pulumirpc.LanguageRuntime.GetRequiredPlugins) in the face of [parameterized
      # providers](parameterized-providers), which as mentioned above can enable multiple instances of the same plugin to
      # provide multiple packages.
      rpc :GetRequiredPackages, ::Pulumirpc::GetRequiredPackagesRequest, ::Pulumirpc::GetRequiredPackagesResponse
      # `Run` executes a Pulumi program, returning information about whether or not the program produced an error.
      rpc :Run, ::Pulumirpc::RunRequest, ::Pulumirpc::RunResponse
      # `GetPluginInfo` returns information about the [plugin](plugins) implementing this language runtime.
      rpc :GetPluginInfo, ::Google::Protobuf::Empty, ::Pulumirpc::PluginInfo
      # `InstallDependencies` accepts a request specifying a Pulumi project and program that can be executed with
      # [](pulumirpc.LanguageRuntime.Run) and installs the dependencies for that program (e.g. by running `npm install`
      # for NodeJS, or `pip install` for Python). Since dependency installation could take a while, and callers may wish
      # to report on its progress, this method returns a stream of [](pulumirpc.InstallDependenciesResponse) messages
      # containing information about standard error and output.
      rpc :InstallDependencies, ::Pulumirpc::InstallDependenciesRequest, stream(::Pulumirpc::InstallDependenciesResponse)
      # `RuntimeOptionsPrompts` accepts a request specifying a Pulumi project and returns a list of additional prompts to
      # ask during `pulumi new`.
      rpc :RuntimeOptionsPrompts, ::Pulumirpc::RuntimeOptionsRequest, ::Pulumirpc::RuntimeOptionsResponse
      # `Template` allows the language runtime to perform additional templating on a newly instantiated project template.
      # For example the Python runtime might want to convert a requirements.txt into a pyproject.toml suitable for use
      # with uv or poetry.
      rpc :Template, ::Pulumirpc::TemplateRequest, ::Pulumirpc::TemplateResponse
      # `About` returns information about the language runtime being used.
      rpc :About, ::Pulumirpc::AboutRequest, ::Pulumirpc::AboutResponse
      # `GetProgramDependencies` computes the set of language-level dependencies (e.g. NPM packages for NodeJS, or Maven
      # libraries for Java) required by a program.
      rpc :GetProgramDependencies, ::Pulumirpc::GetProgramDependenciesRequest, ::Pulumirpc::GetProgramDependenciesResponse
      # `RunPlugin` is used to execute a program written in this host's language that implements a Pulumi
      # [plugin](plugins). It is to plugins what [](pulumirpc.LanguageRuntime.Run) is to programs. Since a plugin is not
      # expected to terminate until instructed/for a long time, this method returns a stream of
      # [](pulumirpc.RunPluginResponse) messages containing information about standard error and output, as well as the
      # exit code of the plugin when it does terminate.
      rpc :RunPlugin, ::Pulumirpc::RunPluginRequest, stream(::Pulumirpc::RunPluginResponse)
      # `GenerateProgram` generates code in this host's language that implements the given [PCL](pcl) program. Unlike
      # [](pulumirpc.LanguageRuntime.GenerateProject), this method *only* generates program code, and does not e.g.
      # generate a `package.json` for a NodeJS project that details how to run that code.
      # [](pulumirpc.LanguageRuntime.GenerateProject), this method underpins ["programgen"](programgen) and the main
      # functionality powering `pulumi convert`.
      rpc :GenerateProgram, ::Pulumirpc::GenerateProgramRequest, ::Pulumirpc::GenerateProgramResponse
      # `GenerateProject` generates code in this host's language that implements the given [PCL](pcl) program and wraps
      # it in some language-specific notion of a "project", where a project is a buildable or runnable artifact. In this
      # sense, `GenerateProject`'s output is a superset of that of [](pulumirpc.LanguageRuntime.GenerateProgram). For
      # instance, when generating a NodeJS project, this method might generate a corresponding `package.json` file, as
      # well as the relevant NodeJS program code. Along with [](pulumirpc.LanguageRuntime.GenerateProgram), this method
      # underpins ["programgen"](programgen) and the main functionality powering `pulumi convert`.
      rpc :GenerateProject, ::Pulumirpc::GenerateProjectRequest, ::Pulumirpc::GenerateProjectResponse
      # `GeneratePackage` generates code in this host's language that implements an [SDK](sdkgen) ("sdkgen") for the
      # given Pulumi package, as specified by a [schema](schema).
      rpc :GeneratePackage, ::Pulumirpc::GeneratePackageRequest, ::Pulumirpc::GeneratePackageResponse
      # `Pack` accepts a request specifying a generated SDK package and packs it into a language-specific artifact. For
      # instance, in the case of Java, it might produce a JAR file from a list of `.java` sources; in the case of NodeJS,
      # a `.tgz` file might be produced from a list of `.js` sources; and so on. Presently, `Pack` is primarily used in
      # [language conformance tests](language-conformance-tests), though it is intended to be used more widely in future
      # to standardise e.g. provider publishing workflows.
      rpc :Pack, ::Pulumirpc::PackRequest, ::Pulumirpc::PackResponse
      # `Link` links local dependencies into a project (program or plugin). The dependencies can be binary artifacts such
      # as wheel or tar.gz files, or source directories. `Link` will update the language specific project files, such as
      # `package.json`, `pyproject.toml`, `go.mod`, etc, to include the dependency. `Link` returns instructions for the
      # user on how to use the linked package in the project.
      rpc :Link, ::Pulumirpc::LinkRequest, ::Pulumirpc::LinkResponse
      # `Cancel` signals the language runtime to gracefully shut down and abort any ongoing operations.
      # Operations aborted in this way will return an error.
      rpc :Cancel, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
