# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/plugin.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "plugin_pb"

module Pulumirpc
  module PackageResolver
    # `PackageResolver` resolves a [](pulumirpc.PackageSpec) -- a user-supplied package reference such as a name,
    # registry coordinate, git URL, or local path, optionally carrying a version and parameters -- into a concrete,
    # downloadable [](pulumirpc.PackageDependency). The engine exposes this service to resource providers as part of the
    # provider handshake so they can resolve packages the same way the CLI does.
    #
    # This is currently unstable and experimental.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.PackageResolver'

      # `ResolvePackage` resolves the given package specification to a concrete package dependency.
      rpc :ResolvePackage, ::Pulumirpc::PackageSpec, ::Pulumirpc::PackageDependency
    end

    Stub = Service.rpc_stub_class
  end
end
