# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/plugin.proto

require 'google/protobuf'


descriptor_data = "\n\x13pulumi/plugin.proto\x12\tpulumirpc\"\x1d\n\nPluginInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\"\xc0\x01\n\x10PluginDependency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06server\x18\x04 \x01(\t\x12=\n\tchecksums\x18\x05 \x03(\x0b\x32*.pulumirpc.PluginDependency.ChecksumsEntry\x1a\x30\n\x0e\x43hecksumsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x1f\n\x0cPluginAttach\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"G\n\x17PackageParameterization\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\xb7\x02\n\x11PackageDependency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06server\x18\x04 \x01(\t\x12>\n\tchecksums\x18\x05 \x03(\x0b\x32+.pulumirpc.PackageDependency.ChecksumsEntry\x12<\n\x10parameterization\x18\x06 \x01(\x0b\x32\".pulumirpc.PackageParameterization\x12\x35\n\textension\x18\x07 \x01(\x0b\x32\".pulumirpc.PackageParameterization\x1a\x30\n\x0e\x43hecksumsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\xbe\x01\n\x0bPackageSpec\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x03(\t\x12\x38\n\tchecksums\x18\x04 \x03(\x0b\x32%.pulumirpc.PackageSpec.ChecksumsEntry\x12\x0e\n\x06server\x18\x05 \x01(\t\x1a\x30\n\x0e\x43hecksumsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32[\n\x0fPackageResolver\x12H\n\x0eResolvePackage\x12\x16.pulumirpc.PackageSpec\x1a\x1c.pulumirpc.PackageDependency\"\x00\x42\x34Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  PluginInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PluginInfo").msgclass
  PluginDependency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PluginDependency").msgclass
  PluginAttach = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PluginAttach").msgclass
  PackageParameterization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PackageParameterization").msgclass
  PackageDependency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PackageDependency").msgclass
  PackageSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PackageSpec").msgclass
end
