# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/resource.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "resource_pb"

module Pulumirpc
  module ResourceMonitor
    # ResourceMonitor is the interface a source uses to talk back to the planning monitor orchestrating the execution.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.ResourceMonitor'

      # GetDeploymentInfo returns the execution context associated with this monitor instance.
      #
      # This is an additive API intended to reduce duplicated state passed through
      # environment variables and per-request protobuf fields. New clients should
      # prefer this over piecemeal feature probing via SupportsFeature.
      #
      # Backward compatibility:
      # - Older monitors may not implement this RPC and will return UNIMPLEMENTED.
      # - Clients should fall back to existing request fields/env vars/SupportsFeature.
      rpc :GetDeploymentInfo, ::Google::Protobuf::Empty, ::Pulumirpc::DeploymentInfo
      rpc :SupportsFeature, ::Pulumirpc::SupportsFeatureRequest, ::Pulumirpc::SupportsFeatureResponse
      rpc :Invoke, ::Pulumirpc::ResourceInvokeRequest, ::Pulumirpc::ResourceInvokeResponse
      rpc :Call, ::Pulumirpc::ResourceCallRequest, ::Pulumirpc::CallResponse
      rpc :ReadResource, ::Pulumirpc::ReadResourceRequest, ::Pulumirpc::ReadResourceResponse
      rpc :RegisterResource, ::Pulumirpc::RegisterResourceRequest, ::Pulumirpc::RegisterResourceResponse
      rpc :RegisterResourceOutputs, ::Pulumirpc::RegisterResourceOutputsRequest, ::Google::Protobuf::Empty
      # Register a resource transform for the stack
      rpc :RegisterStackTransform, ::Pulumirpc::Callback, ::Google::Protobuf::Empty
      # Register an invoke transform for the stack
      rpc :RegisterStackInvokeTransform, ::Pulumirpc::Callback, ::Google::Protobuf::Empty
      # Register a resource hook that can be called by the engine during certain
      # steps of a resource's lifecycle.
      rpc :RegisterResourceHook, ::Pulumirpc::RegisterResourceHookRequest, ::Google::Protobuf::Empty
      # Register an error hook that can be called by the engine when an operation fails and is retryable.
      #
      # Error hooks are a separate type of hook to other life cycle hooks as they have different inputs and outputs.
      rpc :RegisterErrorHook, ::Pulumirpc::RegisterErrorHookRequest, ::Google::Protobuf::Empty
      # Registers a package and allocates a packageRef. The same package can be registered multiple times in Pulumi.
      # Multiple requests are idempotent and guaranteed to return the same result.
      rpc :RegisterPackage, ::Pulumirpc::RegisterPackageRequest, ::Pulumirpc::RegisterPackageResponse
      # SignalAndWaitForShutdown lets the resource monitor know that no more
      # events will be generated. This call blocks until the resource monitor is
      # finished, which will happen once all the steps have executed. This allows
      # the language runtime to stay running and handle callback requests, even
      # after the user program has completed. Runtime SDKs should call this after
      # executing the user's program. This can only be called once.
      rpc :SignalAndWaitForShutdown, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
