# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/resource_status.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2025, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "resource_status_pb"

module Pulumirpc
  module ResourceStatus
    # ResourceStatus is an interface that can be called from a resource provider to update status about a resource.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.ResourceStatus'

      # `PublishViewSteps` is used to publish a series of steps for a view resource.
      # Views can be materialized via create and update steps, and more complex
      # changes, such as replacements, can be modeled as a series of steps.
      # The engine does not actually apply these steps, but rather flows them through
      # the engine such that the view resources are written to state and the view
      # resources are displayed in the UI.
      rpc :PublishViewSteps, ::Pulumirpc::PublishViewStepsRequest, ::Pulumirpc::PublishViewStepsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
