# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/source.proto

require 'google/protobuf'


descriptor_data = "\n\x13pulumi/source.proto\x12\tpulumirpc\";\n\x0eSourcePosition\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\x05\"3\n\nStackFrame\x12%\n\x02pc\x18\x01 \x01(\x0b\x32\x19.pulumirpc.SourcePosition\"3\n\nStackTrace\x12%\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x15.pulumirpc.StackFrameB4Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  SourcePosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SourcePosition").msgclass
  StackFrame = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.StackFrame").msgclass
  StackTrace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.StackTrace").msgclass
end
