# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module ConfigGrpc
    # The inputs to a {ConfigFetcher}.
    class ConfigFetcherArgs < ::Pulumi::Args
    end

    class ConfigFetcher < ::Pulumi::CustomResource
      TYPE = "config-grpc:index:ConfigFetcher"

      def initialize(name, opts: nil, &block)
        args = ConfigFetcherArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def config
        output("config")
      end
    end
  end
end
