# frozen_string_literal: true

source "https://rubygems.org"

gem "pulumi-byepackage", path: "ROOT/artifacts/pulumi-byepackage"
gem "pulumi-hipackage", path: "ROOT/artifacts/pulumi-hipackage"
gem "pulumi", path: "ROOT/artifacts/pulumi"
