# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Goodbye
    # The inputs to a {Goodbye}.
    class GoodbyeArgs < ::Pulumi::Args
    end

    class Goodbye < ::Pulumi::CustomResource
      TYPE = "goodbye:index:Goodbye"

      def initialize(name, opts: nil, &block)
        args = GoodbyeArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
