# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/testing/language.proto for package 'pulumirpc.testing'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "language_pb"

module Pulumirpc
  module Testing
    module LanguageTest
      # LanguageTest is the interface to the pulumi language test framework. This is _highly_ experimental and
      # currently subject to breaking changes without warning.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'pulumirpc.testing.LanguageTest'

        # GetLanguageTests returns a list of all the language tests.
        rpc :GetLanguageTests, ::Pulumirpc::Testing::GetLanguageTestsRequest, ::Pulumirpc::Testing::GetLanguageTestsResponse
        # PrepareLanguageTests prepares the engine to run language tests. It sets up a stable artifacts folder
        # (which should be .gitignore'd) and fills it with the core SDK artifact.
        rpc :PrepareLanguageTests, ::Pulumirpc::Testing::PrepareLanguageTestsRequest, ::Pulumirpc::Testing::PrepareLanguageTestsResponse
        # RunLanguageTest runs a single test of the language plugin.
        rpc :RunLanguageTest, ::Pulumirpc::Testing::RunLanguageTestRequest, ::Pulumirpc::Testing::RunLanguageTestResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
