# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Sync
    # The inputs to a {Block}.
    class BlockArgs < ::Pulumi::Args
    end

    class Block < ::Pulumi::CustomResource
      TYPE = "sync:index:Block"

      def initialize(name, opts: nil, &block)
        args = BlockArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end
    end
  end
end
