# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Keywords
    # The inputs to a {SomeResource}.
    class SomeResourceArgs < ::Pulumi::Args
      property :builtins
      property :lambda
      property :property
    end

    class SomeResource < ::Pulumi::CustomResource
      TYPE = "keywords:index:SomeResource"

      def initialize(name, builtins: nil, lambda: nil, property: nil, opts: nil, &block)
        args = SomeResourceArgs.build({
          builtins: builtins,
          lambda: lambda,
          property: property,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def builtins
        output("builtins")
      end

      # @return [::Pulumi::Output]
      def lambda
        output("lambda")
      end

      # @return [::Pulumi::Output]
      def property
        output("property")
      end
    end
  end
end
