# frozen_string_literal: true

source "https://rubygems.org"

gem "pulumi-module-format", path: "ROOT/artifacts/pulumi-module-format"
gem "pulumi-names", path: "ROOT/artifacts/pulumi-names"
gem "pulumi", path: "ROOT/artifacts/pulumi"
