# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Hipackage
    # The inputs to a {HelloWorld}.
    class HelloWorldArgs < ::Pulumi::Args
    end

    class HelloWorld < ::Pulumi::CustomResource
      TYPE = "hipackage:index:HelloWorld"

      def initialize(name, opts: nil, &block)
        args = HelloWorldArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
