# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module CamelNames
    module CoolModule
      # The inputs to a {SomeResource}.
      class SomeResourceArgs < ::Pulumi::Args
        property :resource_name, wire: :resourceName
        property :the_input, wire: :theInput
      end

      class SomeResource < ::Pulumi::CustomResource
        TYPE = "camelNames:CoolModule:SomeResource"

        def initialize(name, resource_name: nil, the_input: nil, opts: nil, &block)
          args = SomeResourceArgs.build({
            resource_name: resource_name,
            the_input: the_input,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def resource_name
          output("resourceName")
        end

        # @return [::Pulumi::Output]
        def the_output
          output("theOutput")
        end
      end
    end
  end
end
