# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Docs
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :external_enum, wire: :externalEnum
      property :in_, wire: :in
    end

    # {{% ref #/resources/docs:index:Resource %}} is a basic resource. Use {{% ref #/functions/docs:index:fun %}} to set {{% ref#/resources/docs:index:Resource/inputProperties/in %}} using {{% ref #/functions/docs:index:fun/outputs/properties/out %}}.
    class Resource < ::Pulumi::CustomResource
      TYPE = "docs:index:Resource"

      def initialize(name, external_enum: nil, in_: nil, opts: nil, &block)
        args = ResourceArgs.build({
          external_enum: external_enum,
          in_: in_,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def data
        output("data")
      end

      # @return [::Pulumi::Output]
      def external_enum
        output("externalEnum")
      end

      # @return [::Pulumi::Output]
      def in_
        output("in")
      end

      # @return [::Pulumi::Output]
      def out
        output("out")
      end
    end
  end
end
