# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "component/component_callable"
require_relative "component/component_custom_ref_input_output"
require_relative "component/component_custom_ref_output"
require_relative "component/component_foreign_child"
require_relative "component/custom"
