# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module SnakeNames
    module CoolModule
      # The inputs to a {AnotherResource}.
      class AnotherResourceArgs < ::Pulumi::Args
        property :the_input
      end

      class AnotherResource < ::Pulumi::CustomResource
        TYPE = "snake_names:cool_module:another_resource"

        def initialize(name, the_input: nil, opts: nil, &block)
          args = AnotherResourceArgs.build({
            the_input: the_input,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def the_input
          output("the_input")
        end
      end
    end
  end
end
