# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module SnakeNames
    module CoolModule
      # The inputs to a {SomeResource}.
      class SomeResourceArgs < ::Pulumi::Args
        property :nested
        property :the_input
      end

      class SomeResource < ::Pulumi::CustomResource
        TYPE = "snake_names:cool_module:some_resource"

        def initialize(name, nested: nil, the_input: nil, opts: nil, &block)
          args = SomeResourceArgs.build({
            nested: nested,
            the_input: the_input,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def the_output
          output("the_output")
        end
      end
    end
  end
end
