# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Byepackage
    # The inputs to a {GoodbyeWorldComponent}.
    class GoodbyeWorldComponentArgs < ::Pulumi::Args
    end

    class GoodbyeWorldComponent < ::Pulumi::ComponentResource
      TYPE = "byepackage:index:GoodbyeWorldComponent"

      def initialize(name, opts: nil, &block)
        args = GoodbyeWorldComponentArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
