# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "nestedobject/container"
require_relative "nestedobject/map_container"
require_relative "nestedobject/receiver"
require_relative "nestedobject/target"
