# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Bytesource
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :base64
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "bytesource:index:Resource"

      def initialize(name, base64: nil, opts: nil, &block)
        args = ResourceArgs.build({
          base64: base64,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def base64
        output("base64")
      end

      # @return [::Pulumi::Output]
      def bytes
        output("bytes")
      end
    end
  end
end
