# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "enum/deluxe"
require_relative "enum/mod/res"
require_relative "enum/mod/res"
require_relative "enum/res"
