# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Names
    module Mod
      # The inputs to a {Res}.
      class ResArgs < ::Pulumi::Args
        property :value
      end

      class Res < ::Pulumi::CustomResource
        TYPE = "names:mod:Res"

        def initialize(name, value: nil, opts: nil, &block)
          args = ResArgs.build({
            value: value,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def value
          output("value")
        end
      end
    end
  end
end
