# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "keywords/lambda/some_resource"
require_relative "keywords/module/lambda"
require_relative "keywords/some_resource"
