# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Secret
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :private
      property :private_array, wire: :privateArray
      property :private_data, wire: :privateData
      property :private_data_array, wire: :privateDataArray
      property :private_data_map, wire: :privateDataMap
      property :private_map, wire: :privateMap
      property :public
      property :public_data, wire: :publicData
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "secret:index:Resource"

      def initialize(name, private: nil, private_array: nil, private_data: nil, private_data_array: nil, private_data_map: nil, private_map: nil, public: nil, public_data: nil, opts: nil, &block)
        args = ResourceArgs.build({
          private: private,
          private_array: private_array,
          private_data: private_data,
          private_data_array: private_data_array,
          private_data_map: private_data_map,
          private_map: private_map,
          public: public,
          public_data: public_data,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def private
        output("private")
      end

      # @return [::Pulumi::Output]
      def private_array
        output("privateArray")
      end

      # @return [::Pulumi::Output]
      def private_data
        output("privateData")
      end

      # @return [::Pulumi::Output]
      def private_data_array
        output("privateDataArray")
      end

      # @return [::Pulumi::Output]
      def private_data_map
        output("privateDataMap")
      end

      # @return [::Pulumi::Output]
      def private_map
        output("privateMap")
      end

      # @return [::Pulumi::Output]
      def public
        output("public")
      end

      # @return [::Pulumi::Output]
      def public_data
        output("publicData")
      end
    end
  end
end
