# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/codegen/hcl.proto

require 'google/protobuf'


descriptor_data = "\n\x18pulumi/codegen/hcl.proto\x12\x11pulumirpc.codegen\"1\n\x03Pos\x12\x0c\n\x04line\x18\x01 \x01(\x03\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x03\x12\x0c\n\x04\x62yte\x18\x03 \x01(\x03\"e\n\x05Range\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12%\n\x05start\x18\x02 \x01(\x0b\x32\x16.pulumirpc.codegen.Pos\x12#\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x16.pulumirpc.codegen.Pos\"\xbc\x01\n\nDiagnostic\x12\x37\n\x08severity\x18\x01 \x01(\x0e\x32%.pulumirpc.codegen.DiagnosticSeverity\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12)\n\x07subject\x18\x04 \x01(\x0b\x32\x18.pulumirpc.codegen.Range\x12)\n\x07\x63ontext\x18\x05 \x01(\x0b\x32\x18.pulumirpc.codegen.Range*H\n\x12\x44iagnosticSeverity\x12\x10\n\x0c\x44IAG_INVALID\x10\x00\x12\x0e\n\nDIAG_ERROR\x10\x01\x12\x10\n\x0c\x44IAG_WARNING\x10\x02\x42\x32Z0github.com/pulumi/pulumi/sdk/v3/proto/go/codegenb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pulumirpc
  module Codegen
    Pos = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.codegen.Pos").msgclass
    Range = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.codegen.Range").msgclass
    Diagnostic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.codegen.Diagnostic").msgclass
    DiagnosticSeverity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.codegen.DiagnosticSeverity").enummodule
  end
end
