# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pulumi/codegen/loader.proto for package 'codegen'
# Original file comments:
# Copyright 2016, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative "loader_pb"

module Codegen
  module Loader
    # Loader is a service for getting schemas from the Pulumi engine for use in code generators and other tools.
    # This is currently unstable and experimental.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'codegen.Loader'

      # GetSchema tries to find a schema for the given package and version.
      rpc :GetSchema, ::Codegen::GetSchemaRequest, ::Codegen::GetSchemaResponse
    end

    Stub = Service.rpc_stub_class
  end
end
