# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/codegen/mapper.proto

require 'google/protobuf'


descriptor_data = "\n\x1bpulumi/codegen/mapper.proto\x12\x07\x63odegen\"\x95\x01\n\x11GetMappingRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x17\n\x0fpulumi_provider\x18\x02 \x01(\t\x12\x42\n\x15parameterization_hint\x18\x03 \x01(\x0b\x32#.codegen.MapperParameterizationHint\x12\x11\n\tecosystem\x18\x04 \x01(\t\"J\n\x1aMapperParameterizationHint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\"\n\x12GetMappingResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32Q\n\x06Mapper\x12G\n\nGetMapping\x12\x1a.codegen.GetMappingRequest\x1a\x1b.codegen.GetMappingResponse\"\x00\x42\x32Z0github.com/pulumi/pulumi/sdk/v3/proto/go/codegenb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Codegen
  GetMappingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("codegen.GetMappingRequest").msgclass
  MapperParameterizationHint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("codegen.MapperParameterizationHint").msgclass
  GetMappingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("codegen.GetMappingResponse").msgclass
end
