# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Replaceonchanges
    # The inputs to a {ResourceA}.
    class ResourceAArgs < ::Pulumi::Args
      property :replace_prop, wire: :replaceProp
      property :value
    end

    class ResourceA < ::Pulumi::CustomResource
      TYPE = "replaceonchanges:index:ResourceA"

      def initialize(name, replace_prop: nil, value: nil, opts: nil, &block)
        args = ResourceAArgs.build({
          replace_prop: replace_prop,
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def replace_prop
        output("replaceProp")
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
