# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Enum
    # The inputs to a {Deluxe}.
    class DeluxeArgs < ::Pulumi::Args
      property :array_of_enum, wire: :arrayOfEnum
      property :holder
      property :map_of_enum, wire: :mapOfEnum
      property :number_enum, wire: :numberEnum
      property :union_enum, wire: :unionEnum
      property :wordy_enum, wire: :wordyEnum
    end

    class Deluxe < ::Pulumi::CustomResource
      TYPE = "enum:index:Deluxe"

      def initialize(name, array_of_enum: nil, holder: nil, map_of_enum: nil, number_enum: nil, union_enum: nil, wordy_enum: nil, opts: nil, &block)
        args = DeluxeArgs.build({
          array_of_enum: array_of_enum,
          holder: holder,
          map_of_enum: map_of_enum,
          number_enum: number_enum,
          union_enum: union_enum,
          wordy_enum: wordy_enum,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def array_of_enum
        output("arrayOfEnum")
      end

      # @return [::Pulumi::Output]
      def holder
        output("holder")
      end

      # @return [::Pulumi::Output]
      def map_of_enum
        output("mapOfEnum")
      end

      # @return [::Pulumi::Output]
      def number_enum
        output("numberEnum")
      end

      # @return [::Pulumi::Output]
      def union_enum
        output("unionEnum")
      end

      # @return [::Pulumi::Output]
      def wordy_enum
        output("wordyEnum")
      end
    end
  end
end
