# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Enum
    module Mod
      # The inputs to a {Res}.
      class ResArgs < ::Pulumi::Args
        property :int_enum, wire: :intEnum
        property :string_enum, wire: :stringEnum
      end

      class Res < ::Pulumi::CustomResource
        TYPE = "enum:mod:Res"

        def initialize(name, int_enum: nil, string_enum: nil, opts: nil, &block)
          args = ResArgs.build({
            int_enum: int_enum,
            string_enum: string_enum,
          }.compact, &block)

          super(TYPE, name, args.to_h, opts)
        end

        # @return [::Pulumi::Output]
        def int_enum
          output("intEnum")
        end

        # @return [::Pulumi::Output]
        def string_enum
          output("stringEnum")
        end
      end
    end
  end
end
