# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Alpha
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :value
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "alpha:index:Resource"

      def initialize(name, value: nil, opts: nil, &block)
        args = ResourceArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
