# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module AssetArchive
    # The inputs to a {ArchiveResource}.
    class ArchiveResourceArgs < ::Pulumi::Args
      property :value
    end

    class ArchiveResource < ::Pulumi::CustomResource
      TYPE = "asset-archive:index:ArchiveResource"

      def initialize(name, value: nil, opts: nil, &block)
        args = ArchiveResourceArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
