# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Configurer
    # The inputs to a {Configurer}.
    class ConfigurerArgs < ::Pulumi::Args
      property :provider_config, wire: :providerConfig
    end

    # A component that internally constructs a Provider configured with `providerConfig` and exposes it via methods.
    class Configurer < ::Pulumi::ComponentResource
      TYPE = "configurer:index:Configurer"

      def initialize(name, provider_config: nil, opts: nil, &block)
        args = ConfigurerArgs.build({
          provider_config: provider_config,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def provider_config
        output("providerConfig")
      end
    end
  end
end
