# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Configurer
    # The inputs to a {Custom}.
    class CustomArgs < ::Pulumi::Args
      property :value
    end

    # A custom resource whose outputs echo its configured provider's `config` setting.
    class Custom < ::Pulumi::CustomResource
      TYPE = "configurer:index:Custom"

      def initialize(name, value: nil, opts: nil, &block)
        args = CustomArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def config
        output("config")
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
