# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Nestedobject
    # The inputs to a {Container}.
    class ContainerArgs < ::Pulumi::Args
      property :inputs
    end

    class Container < ::Pulumi::CustomResource
      TYPE = "nestedobject:index:Container"

      def initialize(name, inputs: nil, opts: nil, &block)
        args = ContainerArgs.build({
          inputs: inputs,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def details
        output("details")
      end

      # @return [::Pulumi::Output]
      def inputs
        output("inputs")
      end
    end
  end
end
