# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Nestedobject
    # The inputs to a {MapContainer}.
    class MapContainerArgs < ::Pulumi::Args
      property :tags
    end

    class MapContainer < ::Pulumi::CustomResource
      TYPE = "nestedobject:index:MapContainer"

      def initialize(name, tags: nil, opts: nil, &block)
        args = MapContainerArgs.build({
          tags: tags,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def tags
        output("tags")
      end
    end
  end
end
