# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Nestedobject
    # The inputs to a {Receiver}.
    class ReceiverArgs < ::Pulumi::Args
      property :details
    end

    class Receiver < ::Pulumi::CustomResource
      TYPE = "nestedobject:index:Receiver"

      def initialize(name, details: nil, opts: nil, &block)
        args = ReceiverArgs.build({
          details: details,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def details
        output("details")
      end
    end
  end
end
