# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Nestedobject
    # The inputs to a {Target}.
    class TargetArgs < ::Pulumi::Args
      property :name
    end

    class Target < ::Pulumi::CustomResource
      TYPE = "nestedobject:index:Target"

      def initialize(name, name: nil, opts: nil, &block)
        args = TargetArgs.build({
          name: name,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def name
        output("name")
      end
    end
  end
end
