# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module DiscriminatedUnion
    # The inputs to a {Example}.
    class ExampleArgs < ::Pulumi::Args
      property :array_of_union_of, wire: :arrayOfUnionOf
      property :union_of, wire: :unionOf
    end

    class Example < ::Pulumi::CustomResource
      TYPE = "discriminated-union:index:Example"

      def initialize(name, array_of_union_of: nil, union_of: nil, opts: nil, &block)
        args = ExampleArgs.build({
          array_of_union_of: array_of_union_of,
          union_of: union_of,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def array_of_union_of
        output("arrayOfUnionOf")
      end

      # @return [::Pulumi::Output]
      def union_of
        output("unionOf")
      end
    end
  end
end
