# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module PrimitiveDefaults
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :boolean
      property :float
      property :integer
      property :string
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "primitive-defaults:index:Resource"

      def initialize(name, boolean: nil, float: nil, integer: nil, string: nil, opts: nil, &block)
        args = ResourceArgs.build({
          boolean: boolean,
          float: float,
          integer: integer,
          string: string,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def boolean
        output("boolean")
      end

      # @return [::Pulumi::Output]
      def float
        output("float")
      end

      # @return [::Pulumi::Output]
      def integer
        output("integer")
      end

      # @return [::Pulumi::Output]
      def string
        output("string")
      end
    end
  end
end
