# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "names/mod/res"
require_relative "names/mod/res"
require_relative "names/res_array"
require_relative "names/res_list"
require_relative "names/res_map"
require_relative "names/res_resource"
