# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Optionalprimitive
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :boolean
      property :boolean_map, wire: :booleanMap
      property :float
      property :integer
      property :number_array, wire: :numberArray
      property :string
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "optionalprimitive:index:Resource"

      def initialize(name, boolean: nil, boolean_map: nil, float: nil, integer: nil, number_array: nil, string: nil, opts: nil, &block)
        args = ResourceArgs.build({
          boolean: boolean,
          boolean_map: boolean_map,
          float: float,
          integer: integer,
          number_array: number_array,
          string: string,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def boolean
        output("boolean")
      end

      # @return [::Pulumi::Output]
      def boolean_map
        output("booleanMap")
      end

      # @return [::Pulumi::Output]
      def float
        output("float")
      end

      # @return [::Pulumi::Output]
      def integer
        output("integer")
      end

      # @return [::Pulumi::Output]
      def number_array
        output("numberArray")
      end

      # @return [::Pulumi::Output]
      def string
        output("string")
      end
    end
  end
end
