# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Extenumref
    # The inputs to a {Sink}.
    class SinkArgs < ::Pulumi::Args
      property :string_enum, wire: :stringEnum
    end

    class Sink < ::Pulumi::CustomResource
      TYPE = "extenumref:index:Sink"

      def initialize(name, string_enum: nil, opts: nil, &block)
        args = SinkArgs.build({
          string_enum: string_enum,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def string_enum
        output("stringEnum")
      end
    end
  end
end
