# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "index_mod/index_mine/resource"
require_relative "index_mod/index_mine/resource"
