# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

require_relative "module_format/index_resource/resource"
require_relative "module_format/mod/resource"
require_relative "module_format/mod_resource/resource"
