# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Bytesink
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :bytes
      property :expect_base64, wire: :expectBase64
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "bytesink:index:Resource"

      def initialize(name, bytes: nil, expect_base64: nil, opts: nil, &block)
        args = ResourceArgs.build({
          bytes: bytes,
          expect_base64: expect_base64,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def bytes
        output("bytes")
      end

      # @return [::Pulumi::Output]
      def expect_base64
        output("expectBase64")
      end
    end
  end
end
