# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Myext
    # The inputs to a {Greeting}.
    class GreetingArgs < ::Pulumi::Args
    end

    class Greeting < ::Pulumi::CustomResource
      TYPE = "extbase:index:Greeting"

      def initialize(name, opts: nil, &block)
        args = GreetingArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
