# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Myext
    # The inputs to a {GreetingComponent}.
    class GreetingComponentArgs < ::Pulumi::Args
    end

    class GreetingComponent < ::Pulumi::ComponentResource
      TYPE = "extbase:index:GreetingComponent"

      def initialize(name, opts: nil, &block)
        args = GreetingComponentArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
