# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Component
    # The inputs to a {ComponentCustomRefOutput}.
    class ComponentCustomRefOutputArgs < ::Pulumi::Args
      property :value
    end

    # A component resource that accepts an input that is used to create a child custom resource. A reference to this child custom resource is returned.
    class ComponentCustomRefOutput < ::Pulumi::ComponentResource
      TYPE = "component:index:ComponentCustomRefOutput"

      def initialize(name, value: nil, opts: nil, &block)
        args = ComponentCustomRefOutputArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def ref
        output("ref")
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
