# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Component
    # The inputs to a {ComponentCallable}.
    class ComponentCallableArgs < ::Pulumi::Args
      property :value
    end

    # A component resource that has callable methods.
    class ComponentCallable < ::Pulumi::ComponentResource
      TYPE = "component:index:ComponentCallable"

      def initialize(name, value: nil, opts: nil, &block)
        args = ComponentCallableArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
