# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Component
    # The inputs to a {ComponentCustomRefInputOutput}.
    class ComponentCustomRefInputOutputArgs < ::Pulumi::Args
      property :input_ref, wire: :inputRef
    end

    # A component resource that accepts a reference to a custom resource. The input resource's `value` is used to create a child custom resource inside the component, before a reference to this child is returned.
    class ComponentCustomRefInputOutput < ::Pulumi::ComponentResource
      TYPE = "component:index:ComponentCustomRefInputOutput"

      def initialize(name, input_ref: nil, opts: nil, &block)
        args = ComponentCustomRefInputOutputArgs.build({
          input_ref: input_ref,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def input_ref
        output("inputRef")
      end

      # @return [::Pulumi::Output]
      def output_ref
        output("outputRef")
      end
    end
  end
end
