# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Component
    # The inputs to a {ComponentForeignChild}.
    class ComponentForeignChildArgs < ::Pulumi::Args
      property :value
    end

    # A component resource that creates a child custom resource from another package (simple), using the provider passed for that package in the component's providers map.
    class ComponentForeignChild < ::Pulumi::ComponentResource
      TYPE = "component:index:ComponentForeignChild"

      def initialize(name, value: nil, opts: nil, &block)
        args = ComponentForeignChildArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
