# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Output
    # The inputs to a {ComplexResource}.
    class ComplexResourceArgs < ::Pulumi::Args
      property :value
    end

    class ComplexResource < ::Pulumi::CustomResource
      TYPE = "output:index:ComplexResource"

      def initialize(name, value: nil, opts: nil, &block)
        args = ComplexResourceArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def output_array
        output("outputArray")
      end

      # @return [::Pulumi::Output]
      def output_map
        output("outputMap")
      end

      # @return [::Pulumi::Output]
      def output_object
        output("outputObject")
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
