# frozen_string_literal: true

source "https://rubygems.org"

gem "pulumi-nestedobject", path: "ROOT/artifacts/pulumi-nestedobject"
gem "pulumi", path: "ROOT/artifacts/pulumi"
gem "pulumi-simple", path: "ROOT/artifacts/pulumi-simple"
