# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "grpc-tools", "~> 1.65"
  gem "rake", "~> 13.2"
  gem "rbs", "~> 3.9"
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.75"
  gem "rubocop-rspec", "~> 3.5"
  gem "steep", "~> 1.9"
  gem "yard", "~> 0.9"
end
