# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Subpackage
    # The inputs to a {HelloWorldComponent}.
    class HelloWorldComponentArgs < ::Pulumi::Args
    end

    class HelloWorldComponent < ::Pulumi::ComponentResource
      TYPE = "subpackage:index:HelloWorldComponent"

      def initialize(name, opts: nil, &block)
        args = HelloWorldComponentArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def parameter_value
        output("parameterValue")
      end
    end
  end
end
