# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Large
    # The inputs to a {String}.
    class StringArgs < ::Pulumi::Args
      property :value
    end

    class String < ::Pulumi::CustomResource
      TYPE = "large:index:String"

      def initialize(name, value: nil, opts: nil, &block)
        args = StringArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
