# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Constant
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :kind
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "constant:index:Resource"

      def initialize(name, kind: nil, opts: nil, &block)
        args = ResourceArgs.build({
          kind: kind,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def kind
        output("kind")
      end
    end
  end
end
