# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Extbase
    # The inputs to a {Base}.
    class BaseArgs < ::Pulumi::Args
    end

    class Base < ::Pulumi::CustomResource
      TYPE = "extbase:index:Base"

      def initialize(name, opts: nil, &block)
        args = BaseArgs.build({
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def base_value
        output("baseValue")
      end
    end
  end
end
