# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module ConfigEnum
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :the_enum, wire: :theEnum
      property :the_string, wire: :theString
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "config-enum:index:Resource"

      def initialize(name, the_enum: nil, the_string: nil, opts: nil, &block)
        args = ResourceArgs.build({
          the_enum: the_enum,
          the_string: the_string,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def the_enum
        output("theEnum")
      end

      # @return [::Pulumi::Output]
      def the_string
        output("theString")
      end
    end
  end
end
