# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module ComponentPropertyDeps
    # The inputs to a {Component}.
    class ComponentArgs < ::Pulumi::Args
      property :resource
      property :resource_list, wire: :resourceList
      property :resource_map, wire: :resourceMap
    end

    # A component resource that accepts a list of resources. The construct request's property dependencies are returned as an output.
    class Component < ::Pulumi::ComponentResource
      TYPE = "component-property-deps:index:Component"

      def initialize(name, resource: nil, resource_list: nil, resource_map: nil, opts: nil, &block)
        args = ComponentArgs.build({
          resource: resource,
          resource_list: resource_list,
          resource_map: resource_map,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def property_deps
        output("propertyDeps")
      end
    end
  end
end
