# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module SimpleInvoke
    # The inputs to a {StringResource}.
    class StringResourceArgs < ::Pulumi::Args
      property :text
    end

    class StringResource < ::Pulumi::CustomResource
      TYPE = "simple-invoke:index:StringResource"

      def initialize(name, text: nil, opts: nil, &block)
        args = StringResourceArgs.build({
          text: text,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def text
        output("text")
      end
    end
  end
end
