# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module PrimitiveRef
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :data
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "primitive-ref:index:Resource"

      def initialize(name, data: nil, opts: nil, &block)
        args = ResourceArgs.build({
          data: data,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def data
        output("data")
      end
    end
  end
end
