# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Plaincomponent
    # The inputs to a {Component}.
    class ComponentArgs < ::Pulumi::Args
      property :name
      property :settings
    end

    class Component < ::Pulumi::ComponentResource
      TYPE = "plaincomponent:index:Component"

      def initialize(name, name: nil, settings: nil, opts: nil, &block)
        args = ComponentArgs.build({
          name: name,
          settings: settings,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def label
        output("label")
      end
    end
  end
end
