// Copyright 2026, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/pulumi/pulumi/pkg/v3/codegen/schema"
)

// GeneratePackage turns a package schema into the source of a Ruby gem ("sdkgen").
//
// The result is keyed by path relative to the gem root, which is what the engine writes to
// disk and what `pulumi package gen-sdk --language ruby` produces.
func GeneratePackage(
	tool string, pkg *schema.Package, extraFiles map[string][]byte,
	localDependencies map[string]string,
) (map[string][]byte, error) {
	if err := pkg.ImportLanguages(nil); err != nil {
		return nil, err
	}

	g := &packageGenerator{pkg: pkg, tool: tool}
	files := map[string][]byte{}

	for name, contents := range extraFiles {
		files[name] = contents
	}

	// One file per resource, named after the class. Splitting rather than emitting one
	// enormous file is what keeps a large provider navigable -- aws-cdk in Ruby is
	// hundreds of megabytes of source, and a reader has to be able to find a type.
	var requires []string
	for _, resource := range pkg.Resources {
		relative, contents, err := g.genResource(resource)
		if err != nil {
			return nil, err
		}
		files[path.Join("lib", relative)] = contents
		requires = append(requires, strings.TrimSuffix(relative, ".rb"))
	}

	sort.Strings(requires)
	files[path.Join("lib", g.entryPointPath())] = g.genEntryPoint(requires)
	files[g.gemspecName()] = g.genGemspec()
	files["pulumi-plugin.json"] = g.genPluginJSON()
	files["Gemfile"] = g.genGemfile(localDependencies)

	return files, nil
}

type packageGenerator struct {
	pkg  *schema.Package
	tool string
}

// gemName is the published name of the gem: `pulumi-aws` for the `aws` package.
func (g *packageGenerator) gemName() string {
	return "pulumi-" + g.pkg.Name
}

// moduleName is the Ruby module the package's types live under: Pulumi::Aws.
func (g *packageGenerator) moduleName() string {
	return pascalCase(g.pkg.Name)
}

// entryPointPath is the file a program requires: `pulumi/aws.rb` for `require "pulumi/aws"`.
func (g *packageGenerator) entryPointPath() string {
	return path.Join("pulumi", toSnakeCase(g.pkg.Name)+".rb")
}

func (g *packageGenerator) gemspecName() string {
	return g.gemName() + ".gemspec"
}

// resourcePath is where a resource's class lives, derived from its token.
//
// `aws:s3/bucket:Bucket` becomes `pulumi/aws/s3/bucket.rb`. The `index` module is the
// package root and contributes no directory, matching how every other SDK flattens it.
func (g *packageGenerator) resourcePath(token string) (string, []string) {
	module, name := splitToken(token)

	parts := []string{"pulumi", toSnakeCase(g.pkg.Name)}
	namespace := []string{"Pulumi", g.moduleName()}
	if module != "" && module != "index" {
		for _, segment := range strings.Split(module, "/") {
			parts = append(parts, toSnakeCase(segment))
			namespace = append(namespace, pascalCase(segment))
		}
	}

	return path.Join(append(parts, toSnakeCase(name)+".rb")...), namespace
}

// splitToken decomposes `pkg:module/submodule:Name` into its module path and type name.
func splitToken(token string) (module, name string) {
	parts := strings.Split(token, ":")
	if len(parts) < 3 {
		return "", token
	}

	module, name = parts[1], parts[2]
	// A module of the form `s3/bucket` names the type in its last segment; only the
	// leading segments are directories.
	if index := strings.LastIndex(module, "/"); index >= 0 {
		module = module[:index]
	}
	return module, name
}

func (g *packageGenerator) genEntryPoint(requires []string) []byte {
	var out bytes.Buffer
	writeHeader(&out, g.tool)
	out.WriteString("require \"pulumi\"\n\n")
	for _, require := range requires {
		fmt.Fprintf(&out, "require_relative %q\n", strings.TrimPrefix(require, "pulumi/"))
	}
	return out.Bytes()
}

// writeHeader emits the do-not-edit banner every generated file carries.
func writeHeader(out *bytes.Buffer, tool string) {
	fmt.Fprintf(out, "# frozen_string_literal: true\n\n")
	fmt.Fprintf(out, "# *** WARNING: this file was generated by %s. ***\n", tool)
	fmt.Fprintf(out, "# *** Do not edit by hand unless you're certain you know what you are doing! ***\n\n")
}

func (g *packageGenerator) genGemspec() []byte {
	var out bytes.Buffer
	writeHeader(&out, g.tool)

	version := "0.0.0"
	if g.pkg.Version != nil {
		version = g.pkg.Version.String()
	}

	fmt.Fprintf(&out, "Gem::Specification.new do |spec|\n")
	fmt.Fprintf(&out, "  spec.name    = %q\n", g.gemName())
	fmt.Fprintf(&out, "  spec.version = %q\n", version)
	fmt.Fprintf(&out, "  spec.authors = [%q]\n", "Pulumi Corporation")
	fmt.Fprintf(&out, "  spec.summary = %q\n", firstLine(g.pkg.Description, "A Pulumi package"))
	if g.pkg.Homepage != "" {
		fmt.Fprintf(&out, "  spec.homepage = %q\n", g.pkg.Homepage)
	}
	if g.pkg.License != "" {
		fmt.Fprintf(&out, "  spec.license = %q\n", g.pkg.License)
	}
	fmt.Fprintf(&out, "  spec.required_ruby_version = %q\n", ">= 3.3.0")
	fmt.Fprintf(&out, "  spec.files = Dir[%q, %q, %q]\n", "lib/**/*.rb", "sig/**/*.rbs", "pulumi-plugin.json")
	fmt.Fprintf(&out, "  spec.require_paths = [%q]\n", "lib")
	fmt.Fprintf(&out, "\n  spec.add_dependency %q\n", "pulumi")
	fmt.Fprintf(&out, "end\n")
	return out.Bytes()
}

// genPluginJSON emits the file the language host reads to decide which plugin a gem needs.
func (g *packageGenerator) genPluginJSON() []byte {
	plugin := map[string]any{"resource": true, "name": g.pkg.Name}
	if g.pkg.Version != nil {
		plugin["version"] = g.pkg.Version.String()
	}
	if g.pkg.PluginDownloadURL != "" {
		plugin["server"] = g.pkg.PluginDownloadURL
	}

	contents, err := json.MarshalIndent(plugin, "", "  ")
	if err != nil {
		// The map holds only strings and a bool, so this cannot fail.
		panic(err)
	}
	return append(contents, '\n')
}

func (g *packageGenerator) genGemfile(localDependencies map[string]string) []byte {
	var out bytes.Buffer
	out.WriteString("# frozen_string_literal: true\n\nsource \"https://rubygems.org\"\n\ngemspec\n")

	// A locally built core SDK is how the conformance harness -- and a developer working
	// from a checkout -- points the generated gem at something not yet published.
	if path, ok := localDependencies["pulumi"]; ok {
		fmt.Fprintf(&out, "\ngem %q, path: %q\n", "pulumi", path)
	}
	return out.Bytes()
}

func firstLine(text, fallback string) string {
	line, _, _ := strings.Cut(strings.TrimSpace(text), "\n")
	if line == "" {
		return fallback
	}
	return line
}
