# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Names
    # The inputs to a {ResMap}.
    class ResMapArgs < ::Pulumi::Args
      property :value
    end

    class ResMap < ::Pulumi::CustomResource
      TYPE = "names:index:ResMap"

      def initialize(name, value: nil, opts: nil, &block)
        args = ResMapArgs.build({
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
