# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Plain
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :data
      property :data_list, wire: :dataList
      property :non_plain_data, wire: :nonPlainData
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "plain:index:Resource"

      def initialize(name, data: nil, data_list: nil, non_plain_data: nil, opts: nil, &block)
        args = ResourceArgs.build({
          data: data,
          data_list: data_list,
          non_plain_data: non_plain_data,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def data
        output("data")
      end

      # @return [::Pulumi::Output]
      def data_list
        output("dataList")
      end

      # @return [::Pulumi::Output]
      def non_plain_data
        output("nonPlainData")
      end
    end
  end
end
