# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Namespaced
    # The inputs to a {Resource}.
    class ResourceArgs < ::Pulumi::Args
      property :resource_ref, wire: :resourceRef
      property :value
    end

    class Resource < ::Pulumi::CustomResource
      TYPE = "namespaced:index:Resource"

      def initialize(name, resource_ref: nil, value: nil, opts: nil, &block)
        args = ResourceArgs.build({
          resource_ref: resource_ref,
          value: value,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def resource_ref
        output("resourceRef")
      end

      # @return [::Pulumi::Output]
      def value
        output("value")
      end
    end
  end
end
