# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

Gem::Specification.new do |spec|
  spec.name    = "pulumi-sync"
  spec.version = "3.0.0-alpha.1.internal+exp.sha.2143768"
  spec.authors = ["Pulumi Corporation"]
  spec.summary = "A Pulumi package"
  spec.required_ruby_version = ">= 3.3.0"
  spec.files = Dir["lib/**/*.rb", "sig/**/*.rbs", "pulumi-plugin.json"]
  spec.require_paths = ["lib"]

  spec.add_dependency "pulumi"
end
