# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Union
    # The inputs to a {EnumOutput}.
    class EnumOutputArgs < ::Pulumi::Args
      property :name
    end

    class EnumOutput < ::Pulumi::CustomResource
      TYPE = "union:index:EnumOutput"

      def initialize(name, name: nil, opts: nil, &block)
        args = EnumOutputArgs.build({
          name: name,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def name
        output("name")
      end

      # @return [::Pulumi::Output]
      def type
        output("type")
      end
    end
  end
end
