# frozen_string_literal: true

# *** WARNING: this file was generated by pulumi-language-ruby. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

require "pulumi"

module Pulumi
  module Union
    # The inputs to a {Example}.
    class ExampleArgs < ::Pulumi::Args
      property :map_map_union_property, wire: :mapMapUnionProperty
      property :string_enum_union_list_property, wire: :stringEnumUnionListProperty
      property :string_or_integer_property, wire: :stringOrIntegerProperty
      property :typed_enum_property, wire: :typedEnumProperty
    end

    class Example < ::Pulumi::CustomResource
      TYPE = "union:index:Example"

      def initialize(name, map_map_union_property: nil, string_enum_union_list_property: nil, string_or_integer_property: nil, typed_enum_property: nil, opts: nil, &block)
        args = ExampleArgs.build({
          map_map_union_property: map_map_union_property,
          string_enum_union_list_property: string_enum_union_list_property,
          string_or_integer_property: string_or_integer_property,
          typed_enum_property: typed_enum_property,
        }.compact, &block)

        super(TYPE, name, args.to_h, opts)
      end

      # @return [::Pulumi::Output]
      def map_map_union_property
        output("mapMapUnionProperty")
      end

      # @return [::Pulumi::Output]
      def string_enum_union_list_property
        output("stringEnumUnionListProperty")
      end

      # @return [::Pulumi::Output]
      def string_or_integer_property
        output("stringOrIntegerProperty")
      end

      # @return [::Pulumi::Output]
      def typed_enum_property
        output("typedEnumProperty")
      end
    end
  end
end
